server:
  address: ${SERVER_ADDRESS:localhost}
  port: ${SERVER_PORT:9005}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api/v1}

eureka:
  instance:
    hostname: ${APPLICATION_NAME:user-service}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_DEFAULT_ZONE:http://localhost:9001/api/eureka/}

spring:
  application:
    name: ${APPLICATION_NAME:user-service}