server:
  address: ${SERVER_ADDRESS:localhost}
  port: ${SERVER_PORT:9003}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api/v1}

spring:
  application:
    name: ${APPLICATION_NAME:notification-service}
  mail:
    host: smtp.gmail.com
    port: 587
    username: global.storage.info@gmail.com
    password: tbhboaibjuvjvdpf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  instance:
    hostname: ${APPLICATION_NAME:notification-service}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_DEFAULT_ZONE:http://localhost:9001/api/eureka/}