server:
  port: 8083
  servlet:
    context-path: "/api"

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8081/api/eureka/"

spring:
  application:
    name: notification-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: global.storage.info@gmail.com
    password: tbhboaibjuvjvdpf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true