version: "3.5"

networks:
  glos-app-network:
    driver: bridge

services:
  eureka-server:
    build:
      context: .
      dockerfile: ./eureka-service/Dockerfile
    image: eureka-server
    container_name: eureka-server
    restart: always
    ports:
      - "8081:8081"
    networks:
      - glos-app-network
