server:
  address: ${SERVER_ADDRESS:localhost}
  port: ${SERVER_PORT:9006}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api/v1}

eureka:
  instance:
    hostname: ${APPLICATION_NAME:auth-service}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_DEFAULT_ZONE:http://localhost:9001/api/eureka/}

spring:
  application:
    name: ${APPLICATION_NAME:auth-service}