server:
  address: ${SERVER_ADDRESS:localhost}
  port: ${SERVER_PORT:9006}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api/v1}

eureka:
  instance:
    hostname: ${APPLICATION_NAME:auth-service}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_DEFAULT_ZONE:http://localhost:9001/api/eureka/}

spring:
  application:
    name: ${APPLICATION_NAME:auth-service}
  cloud:
    openfeign:
      client:
        config:
          user:
            url: http://localhost:9005/api/v1
          user-database:
            url: http://localhost:8080/api/v1

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:"583773d0820a96e7b12c0bc72b0e132224552a82ad95953778bfacfa7d5a4f1a"}
    access: ${SECURITY_JWT_ACCESS_EXPIRED:3600000}
    refresh: ${SECURITY_JWT_REFRESH_EXPIRED:2592000000}

jwt:
  secret:
    key: "583773d0820a96e7b12c0bc72b0e132224552a82ad95953778bfacfa7d5a4f1a"