server:
  port: 9006
  servlet:
    context-path: "/api/v1/users"

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8081/api/eureka/"

spring:
  application:
    name: group-service

