server:
  address: ${SERVER_ADDRESS:localhost}
  port: ${SERVER_PORT:9006}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api/v1}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_DEFAULT_ZONE:http://localhost:9001/api/eureka/}

spring:
  application:
    name: ${APPLICATION_NAME:group-service}
  cloud:
    openfeign:
      client:
        config:
          group:
            url: http://localhost:8080/api/v1/groups
          user:
            url: http://localhost:8080/api/v1/users
          accessType:
            url: http://localhost:8080/api/v1/access-types
