server:
  address: ${SERVER_ADDRESS:localhost}
  port: ${SERVER_PORT:8083}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api/v1}

spring:
  application:
    name: ${APPLICATION_NAME:comment-service}
  cloud:
    openfeign:
      client:
        config:
          comment:
            url: http://localhost:8080/api/v1/comments
          users:
            url: http://localhost:8080/api/v1/users
          files:
            url: http://localhost:9006/api/v1/files
          repositories:
            url: http://localhost:9006/api/v1/repositories