server:
  address: ${SERVER_ADDRESS:localhost}
  port: ${SERVER_PORT:8083}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api}

spring:
  application:
    name: ${APPLICATION_NAME:comment-service}


