export const authActionTypes = {
    SET_LOADING: 'SET_LOADING',
    SET_USER: 'SET_USER',
    SET_ERROR: 'SET_ERROR',
    LOG_OUT: 'LOG_OUT',
    REGISTER: 'REGISTER',
    UPDATE_USER: 'UPDATE_USER',
    SET_UPDATE_STATUS: 'SET_UPDATE_STATUS',
}