server:
  address: ${SERVER_ADDRESS:localhost}
  port: ${SERVER_PORT:9001}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api}

spring:
  application:
    name: ${APPLICATION_NAME:eureka-service}

eureka:
  instance:
    hostname: ${APPLICATION_NAME:eureka-service}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_CLIENT_DEFAULT_ZONE:http://localhost:9001/api/eureka}