server:
  port: 8084
  servlet:
    context-path: "/api"

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8081/api/eureka/"

spring:
  application:
    name: operation-service
