server:
  address: ${SERVER_ADDRESS:localhost}
  port: ${SERVER_PORT:9004}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api}

eureka:
  instance:
    hostname: ${APPLICATION_NAME:feed-service}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_DEFAULT_ZONE:http://localhost:9001/api/eureka/}

spring:
  application:
    name: ${APPLICATION_NAME:feed-service}