server:
  server:
    address: ${SERVER_ADDRESS:localhost}
    port: ${SERVER_PORT:9005}
    servlet:
      context-path: ${SERVER_CONTEXT_PATH:/api/v1}

spring:
  application:
    name: ${APPLICATION_NAME:file-storage-service}

eureka:
  instance:
    hostname: ${APPLICATION_NAME:api-gateway}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_DEFAULT_ZONE:http://localhost:9001/api/eureka/}