server:
  address: ${SERVER_ADDRESS:localhost}
  port: ${PORT:9011}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api/v1}

spring:
  application:
    name: ${APPLICATION_NAME:access-service}
  cloud:
    openfeign:
      client:
        config:
          accessTypes:
            url: ${DATABASE_API_SERVICE_URL:http://localhost:8080/api/v1}/access-types
          files:
            url: ${FILE_MANAGER_SERVICE_URL:http://localhost:9010/api/v1}/files
          repositories:
            url: ${FILE_MANAGER_SERVICE_URL:http://localhost:9010/api/v1}/repositories
          secureCodes:
            url : ${DATABASE_API_SERVICE_URL:http://localhost:8080/api/v1}/secure-codes
          auth:
            url : ${AUTH_SERVICE:http://localhost:9006/api/v1}

eureka:
  instance:
    hostname: ${APPLICATION_NAME:access-service}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_DEFAULT_ZONE:http://localhost:9001/api/eureka/}