server:
  address: ${SERVER_ADDRESS:localhost}
  port: ${SERVER_PORT:9011}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api/v1}

spring:
  application:
    name: ${APPLICATION_NAME:access-service}
  cloud:
    openfeign:
      client:
        config:
          accessTypes:
            url: http://localhost:8080/api/v1/access-types
          files:
            url: http://localhost:9010/api/v1/files
          repositories:
            url: http://localhost:9010/api/v1/repositories
          secureCodes:
            url : http://localhost:8080/api/v1/secure-codes
          auth:
            url : http://localhost:9006/api/v1/

eureka:
  instance:
    hostname: ${APPLICATION_NAME:access-service}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_DEFAULT_ZONE:http://localhost:9001/api/eureka/}